config/routes.rb
Calpal::Application.routes.draw do
  root :to => 'welcome#index'

  resources :users, :foods, :meals

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/food.rb
# == Schema Information
#
# Table name: foods
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  calories   :integer
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Food < ActiveRecord::Base
  attr_accessible :name, :image, :calories
  has_and_belongs_to_many :meals
end

app/models/meal.rb
# == Schema Information
#
# Table name: meals
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  meal_date   :date
#  meal_time   :time
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Meal < ActiveRecord::Base
  attr_accessible :name, :description, :meal_date, :meal_time
  has_and_belongs_to_many :foods
  belongs_to :user, :inverse_of => :meals

  def total_cals
    cals = []
    self.foods.each {|f| cals << f.calories}
    cals.reduce(:+)
  end

  def food_images
    food_images = []
    self.foods.each {|f| food_images << f.image}
    food_images
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  target          :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :name, :email, :password, :password_confirmation, :target
  has_many  :meals#, :inverse_of => :users
  has_many  :foods, :through => :meals
  validates :name, :email, :uniqueness => true, :presence => true
  validates :target, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authentication

  private
  def authentication
    @auth = User.find(session[:user_id]) if session[:user_id].present?
  end

  def check_if_logged_in
    redirect_to(login_path) if @auth.nil?
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_filter :check_if_logged_in

  def index
    @foods = @auth.foods
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @meals = @auth.meals
    @foods = @auth.foods.uniq
  end

  def show
    @meals = Meal.find(params[:id])
  end

  def new
    @meal = Meal.new
  end

  def edit
    @meal = Meal.find(params[:id])
  end

  def create
    id = params[:id]
    name = params[:name]
    description = params[:description]
    foods = params[:food_picker]
    meal_date = params[:meal_date]
    meal_time = params[:meal_time]

    meal = Meal.create(:name => name, :description => description, :meal_time => meal_time, :meal_date => meal_date )
    @auth.meals << meal
    foods.split(',').each.map do |f|
      food = Food.find(f.to_i)
      meal.foods << food
    end

    render :json => meal.to_json(:methods => [:total_cals, :food_images])
  end

  def update
    meal = Meal.find([:id])
    meal.update_attributes
  end

  def destroy
    meal = Meal.find([:id])
    meal.delete
    redirect_to(meals)
  end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.where(:email => params[:email]).first
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to(root_path)
    else
      flash[:notice] = 'Nope. Try again.'
      redirect_to(login_path)
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to(root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :check_if_logged_in, :except => [:new, :create]
  def new
    @user = User.new
  end

  def edit
    @user = @auth
    render :new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to(root_path)
    else
      render :new
    end
  end

  def update
    @user = @auth
    if @user.update_attributes(params[:user])
      redirect_to(root_path)
    else
      render :new
    end
  end

  private #because it's not an action
  def check_if_logged_in
    redirect_to(root_path) if @auth.nil?
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/index.html.haml
.row
  .one.columns
  .eleven.columns
    %h1 Foods
.row
  .one.columns
  .six.columns
    %ul
      - @foods.each do |food|
        %li
          = link_to(food.name, food)
  .five.columns

app/views/foods/new.html.haml
.row
  .one.columns
  .eleven.columns
    %h1 Add food

.row
  .one.columns
  .six.columns
    = form_for @food do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :calories
      = f.text_field :calories
      = f.label :image
      = f.text_field :image
      = f.submit nil, :class => 'button radius'

  .five.columns

app/views/foods/show.html.haml
.row
  .one.columns
  .six.columns
    %h2= @food.name
    %br
    = image_tag(@food.image)
    %br
    %h3== #{@food.calories} calories
  .five.columns

app/views/layouts/_footer.html.erb
<!-- Footer -->

  <footer class="row">
  <div class="twelve columns"><hr />
      <div class="row">

        <div class="six columns">
            <p>&copy; 2013 your mom.</p>
        </div>

        <div class="six columns">
            <ul class="link-list right">
              <li><a href="http://twitter.com/khalua">Twitter</a></li>
              <li><a href="http://yerko.com">Yerko</a></li>
            </ul>
        </div>

      </div>
  </div>
  </footer>

app/views/layouts/_nav.html.erb
  <!-- Navigation -->

  <nav class="top-bar fixed">
    <ul>
      <li class="name"><h1><a href="/">Calpal</span></a></h1></li>
      <li class="toggle-topbar"><a href="#"></a></li>
    </ul>

    <section>
      <ul class="left">
        <% if !@auth.present? %>
          <li><%= link_to("Log in", login_path) %></li>
          <li><%= link_to("Create Account", new_user_path) %></li>
        <% else %>
          <li><%= link_to('Foods', foods_path) %></li>
          <li><%= link_to('Meals', meals_path) %></li>
        <% end %>
      </ul>

      <ul class="right">
        <% if @auth.present? %>
          <li><%= link_to('Logout: ' + @auth.name, login_path, :method => :delete, :confirm => 'see ya?') %></li>
        <% end %>
        <!-- <li class="has-dropdown">
          <a href="#">Users Admin</a>
          <ul class="dropdown">
            <li><%#= link_to("Show Users", users_path) %> </li>
          </ul>
        </li>
      </ul> -->
    </section>
  </nav>

  <!-- End Navigation -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CalPal</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<%= render :partial => "layouts/nav" %>
<body>

  <% if flash[:notice].present? %>
  <div class='row'>
    <div class="five columns alert-box alert">
      <%= flash[:notice] %>
    </div>
    <div class="seven columns"></div>
  </div>
  <% end %>

<%= yield %>


<%= render :partial => "layouts/footer" %>
</body>
</html>

app/views/meals/index.html.haml
.row
  .one.columns
  .eleven.columns
    %h1 Your meals
.row
  .one.columns
  .six.columns
    %table.meals
      %thead
        %tr
          %th Date
          %th Meal
          %th Food(s)
          %th Total calories
      %tbody
        - @meals.each do |meal|
          %tr
            %td= meal.meal_date
            %td= meal.name
            %td{:class => 'food_thumbnail'}= meal.foods.map {|x| image_tag(x.image.to_s, :size => '50x50') }.join(" ").html_safe
            %td= meal.total_cals
  .five.columns
    .controls
      .new
        = button_tag 'New meal', :id => 'show_form', :class => 'button success radius tiny'
      .form.hide
        = form_tag do
          = label_tag 'name'
          = text_field_tag 'name'
          = label_tag 'description'
          = text_field_tag 'description'
          = label_tag 'foods_eaten'
          = text_field_tag 'food_picker'
          = label_tag 'meal_date'
          = text_field_tag 'datepicker', nil, :dateFormat => 'yy-mm-dd', :name => 'meal_date'
          = label_tag 'meal_time'
          = text_field_tag 'meal_time'
          = hidden_field_tag 'meal_id'
          = link_to('Cancel','#', :id => 'hide_form', :class => 'button alert radius tiny')
          = submit_tag 'Add new meal', :id => 'create_meal', :class => 'button radius tiny'


#foods.reveal-modal
  %h2 Select foods eaten
  %p.lead Wassup
  - @foods.each do |food|
    = image_tag(food.image, :size => "50x50", :alt => food.id)
  %br
  = link_to("Done", "#", :id => 'done_adding_foods', :class => 'button alert radius tiny close-reveal-modal')
  %a.close-reveal-modal &#215;

app/views/meals/new.html.haml
.row
  .one.columns
  .eleven.columns
    %h1 Add food

.row
  .one.columns
  .six.columns
    = form_for @meal do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :description
      = f.text_field :description
      = f.label :eat_date
      = f.text_field :eat_date
      = f.label :eat_time
      = f.text_field :eat_time
      = f.submit nil, :class => 'button radius'

  .five.columns

app/views/session/new.html.haml
.row
  .one.columns
  .four.columns
    %h1 Log in
  .seven.columns
.row
  .one.columns
  .four.columns
    = form_tag '/login' do
      = label_tag 'email'
      = text_field_tag 'email', nil, :autofocus => true
      = label_tag 'password'
      = password_field_tag 'password'
      = submit_tag  'Login to CalPal', :class => 'button radius'
  .seven.columns

app/views/users/new.html.haml
.row
  .one.columns
  .eight.columns
    %h1 Create an account
  .three.columns

.row
  .one.columns
  .five.columns
    - if @user.errors.any?
      %ol
        - @user.errors.full_messages.each do |msg|
          %li
            %span.label.alert.radius= msg

    = form_for @user do |f|
      = f.label :name
      = f.text_field :name, :autofocus => true
      = f.label :email
      = f.text_field :email
      = f.label :password
      = f.password_field :password
      = f.label :password_confirmation
      = f.password_field :password_confirmation
      = f.label :target, 'Target calories per day'
      = f.text_field :target
      = f.submit nil, :class => 'button radius' #nil has to be there for the text to change
  .six.columns